// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lgmuifihxxgiuvqbinpk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxnbXVpZmloeHhnaXV2cWJpbnBrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0MTE3MjYsImV4cCI6MjA3MDk4NzcyNn0.JYGk5x6XyJ7tReqMFGNHjzTZlX3F2QbpKoHSvFv3pCA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});